### ISSUE TITLE
[xchain-cli]query chain status failed

### ISSUE THREAD

**Issue by Karenlrx** [xuperchain/xupercore#237]
when I use cmd in README.MD: `$$./bin/xchain-cli status -H :36301.`
An error will be reported that `command exec failed.err:query chain status failed.`
It seems that I need to use command【 `$$./bin/xchain-cli chain status -H : xxxx`】by using `-h`.
How can I get the correct port? it seems is not the port from the file of `network.yaml`.

**Comment by icexin** [comment]
Try the `rpcPort` field in server.yaml

**Comment by Karenlrx** [comment]
> Try the `rpcPort` field in server.yaml

still error when I use `rpcPort: 36101`.
when I check the node's log, I ensure the network is working. 
if I use '$$./bin/xchain-cli status',the cmd show that:
![image](https://user-images.githubusercontent.com/38199201/131822862-1215976a-10fc-4b7c-80c8-793238d56a40.png)

But still can't use the `cli` watch the status specify port.

**Comment by KenianShi** [comment]
the correct host is "127.0.0.1:36101", not ":36101".
please have a try with "-H 127.0.0.1:36101" if you run the xuperChain in your local machine.

**Comment by Karenlrx** [comment]
> the correct host is "127.0.0.1:36101", not ":36101".
> please have a try with "-H 127.0.0.1:36101" if you run the xuperChain in your local machine.

Thx,it's solved.
